"""FastAPI app — all endpoints generated by create_app()."""
try:
    from openenv.core.env_server.http_server import create_app
except Exception as e:  # pragma: no cover
    raise ImportError(
        "openenv is required. Install with 'uv sync'"
    ) from e

try:
    from ..models import PromptAction, PromptObservation
    from .prompt_opt_env_environment import PromptOptEnvEnvironment
except (ModuleNotFoundError, ImportError):
    from models import PromptAction, PromptObservation
    from server.prompt_opt_env_environment import PromptOptEnvEnvironment

app = create_app(
    PromptOptEnvEnvironment,
    PromptAction,
    PromptObservation,
    env_name="prompt_opt_env",
    max_concurrent_envs=1,
)

# ── Mount custom Web UI for HuggingFace deployment ───────────────────────────
try:
    try:
        from prompt_opt_env.web_ui import landing, home, optimize, _write_templates
    except Exception:
        try:
            from ..web_ui import landing, home, optimize, _write_templates
        except Exception:
            from web_ui import landing, home, optimize, _write_templates
    from fastapi.responses import HTMLResponse
    
    # Remove any existing root route injected dynamically by openenv push
    app.router.routes = [r for r in app.router.routes if getattr(r, "path", None) not in ["/", "/app", "/optimize"]]

    _write_templates()
    
    # Add routes and force them to the absolute front of the routing table
    app.get("/", response_class=HTMLResponse)(landing)
    app.router.routes.insert(0, app.router.routes.pop())
    
    app.get("/app", response_class=HTMLResponse)(home)
    app.router.routes.insert(0, app.router.routes.pop())
    
    app.post("/optimize", response_class=HTMLResponse)(optimize)
    app.router.routes.insert(0, app.router.routes.pop())
    
    print("[INFO] Successfully mounted Custom Dark UI on / with highest priority")
except Exception as e:
    print(f"[WARNING] Web UI could not be mounted: {e}")



def main(host: str = "0.0.0.0", port: int = 8000):
    """Entry point for direct execution via uv run or python -m."""
    import uvicorn
    uvicorn.run(app, host=host, port=port)


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--port", type=int, default=8000)
    args = parser.parse_args()
    main(port=args.port)
