"""FastAPI app — all endpoints generated by create_app()."""
try:
    from openenv.core.env_server.http_server import create_app
except Exception as e:  # pragma: no cover
    raise ImportError(
        "openenv is required. Install with 'uv sync'"
    ) from e

try:
    from ..models import PromptAction, PromptObservation
    from .prompt_opt_env_environment import PromptOptEnvEnvironment
except (ModuleNotFoundError, ImportError):
    from models import PromptAction, PromptObservation
    from server.prompt_opt_env_environment import PromptOptEnvEnvironment

app = create_app(
    PromptOptEnvEnvironment,
    PromptAction,
    PromptObservation,
    env_name="prompt_opt_env",
    max_concurrent_envs=1,
)


def main(host: str = "0.0.0.0", port: int = 8000):
    """Entry point for direct execution via uv run or python -m."""
    import uvicorn
    uvicorn.run(app, host=host, port=port)


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--port", type=int, default=8000)
    args = parser.parse_args()
    main(port=args.port)
